### ISSUE TITLE
Getting "Running the contributed command: 'extension.generateDoc' failed." Error on Run

### ISSUE THREAD

**Issue by EKKOING** [KeeganBruer/javadoc-generator#1]
Upon calling the command from the palette it just gives me the above error. Any suggestions?

I don't have any fix or further info on the problem.

**Comment by KeeganBruer** [comment]
That error alone doesn't give me a lot of information because that error just means that my extension didn't work correctly for that instance. My main guess would be that the extension cannot find your version of java. The program currently requires that you have java downloaded and your JAVA_HOME system variable configured correctly. 

I am currently working on making the extension a stand alone system which should fix your issue.

**Comment by KeeganBruer** [comment]
I have now added a stand alone generator that will not require java to be already installed. This should fix your issue, but feel free to reopen this issue or open a new one if the problem persists.
