### ISSUE TITLE
javadoc-generator error

### ISSUE THREAD

**Issue by Per6** [KeeganBruer/javadoc-generator#19]
<img width="695" alt="Screenshot 2022-06-29 173551" src="https://user-images.githubusercontent.com/76496529/176478577-fb678543-02a5-42fa-8ac5-807acb15c950.png">
This error comes up when i try to use it
might have something to do with me having a jre file instead of jdk (the error is for 4 files)
<img width="130" alt="Screenshot 2022-06-29 173623" src="https://user-images.githubusercontent.com/76496529/176478864-6184949c-ffe9-4f1c-a403-ddfe49319bd5.png">
if i don't type in any path for my .java files this happens:
<img width="394" alt="Screenshot 2022-06-29 181709" src="https://user-images.githubusercontent.com/76496529/176486050-faaed020-39be-4880-b1ad-b2365ab640e3.png">

**Comment by BeboKhouja** [comment]
I also had the same issue.

**Comment by Arnseb** [comment]
Same here. It shows unexpected token for "-d" and the last part of the path has a backslash.

**Comment by flow1990** [comment]
Is here a fix? I would really love to use this tool

**Comment by KeeganBruer** [comment]
@flow1990 Sorry, I'm not in college anymore, so I don't have time to run down this issue. It seems to arise from misuse of the tool as the source path should be the directory of the Java source files. Ie. The src folder, not the folder containing a jre. The jre is packaged with the project.

Edit, it assumes you are in the java projects root folder. And then it looks for a src folder. Which is why the path in the error screenshot shows Desktop\src/src. Id assume they were trying to run this from the src folder and not from the Desktop folder. If you need further details on how to use, the readme should explain how to use the project
