### ISSUE TITLE
Suggestion: Include/Exclude directories

### ISSUE THREAD

**Issue by LeducNic** [KeeganBruer/javadoc-generator#28]
Instead of listing all the files, you can only list the submodules, like in the command line generated by Javadoc-Tools.  

But the must useful feature would be an exclude file or directory list to generate Javadoc only for the submodules that we want and avoid resource or test folders.

**Comment by KeeganBruer** [comment]
That's the plan in the long run. I'm currently just scanning for .Java files, because there have been some reported issues with some submodule detection in the last version. I want to switch out the config file for a type of hybrid JSON, so I can define more fine-tune control over the scanning process. For now, the basic setup was to hopefully provide more transparency of the underlying command for self-debugging.

**Comment by KeeganBruer** [comment]
Alright, published a new update to get the functionality out to you before the bigger update I will be releasing once the features are more stable. Should be out shortly once it's verified by vscode's marketplace

**Comment by KeeganBruer** [comment]
As this issue is more focused on the exclude sub-directories, and not specifically the listing files instead of modules, I am going to close this. Feel free to reopen, or create a new issue, if the implemented exclude functionality is not what was requested. 

I will be opening an issue related to the sub module listing soon.

Best,
Keegan
