### ISSUE TITLE
erroe

### ISSUE THREAD

**Issue by hafnerw** [KeeganBruer/javadoc-generator#5]
it just says: 
'extension.generateStandAloneDoc' failed.

and nothing happens

**Comment by phil9987** [comment]
same here, any resolution to this? Am I missing any setup steps?

**Comment by sovapCGI** [comment]
same here:
Running the contributed command: 'extension.generateStandAloneDoc' failed.

**Comment by sovap** [comment]
same here: 
Running the contributed command: 'extension.generateStandAloneDoc' failed.

It happens for both possibilities:
1) Built-In Generator 
2) System Generator

**Comment by KeeganBruer** [comment]
Hey y'all, just woke up for the day. Going to try to push an update for the extension in a few hours. This error is a general error and doesn't give me a good idea of what went wrong. I'm guessing that the compiler maybe having trouble either finding a javadoc compiler or the files ment to compile. For now, make sure you have opened and run at least one .Java file from the directory your trying to compile as it uses the current working directory to compile.

**Comment by phil9987** [comment]
Hi Keegan, thanks for your quick reply. I tried entering the directory where my main java file is located in the terminal as well as opening it in visual studio. In the window I have opened the project folder and because it is a gradle project there is no .Java file in the root directory. Do I have to "open folder" the folder where a .java file is located for it to work properly?

**Comment by KeeganBruer** [comment]
Sorry for the late reply, been at uni all day . In VSCode, you should open up the .java file where "public static void main(String[] args)" is located. I'm trying to fix the file location part of the compiler so that it finds gradle and maven projects automatically but currently the compiler currently looks at the working directory of the currently opened .java file to try and locate the rest.

**Comment by jorgematiasbc** [comment]
Having the problem too. How's the issue going ?
I wouldn't mind making an extra step manually.
(I'm using it for my playground projects, no hurry ^-^)

**Comment by KeeganBruer** [comment]
I have been working on a new version that adds a lot more customization options and should help with these issues. 

I've realized the old version of the extension doesn't have good error reporting so it is hard to tell where all the issues stem from. 

Thanks for being patient, final year in university!

**Comment by KeeganBruer** [comment]
> Hi Keegan, thanks for your quick reply. I tried entering the directory where my main java file is located in the terminal as well as opening it in visual studio. In the window I have opened the project folder and because it is a gradle project there is no .Java file in the root directory. Do I have to "open folder" the folder where a .java file is located for it to work properly?

I also wanted to mention that the compilation is not based on any gradle or maven files. The previous version was looking, relative to the workspace directory, in the ./src directory for package folders that contained the .java files. The new version allows for the entering of a folder so it is not restricted to just ./src. But both are still restricted by the folder structure:
- ./src
    - ./src/test
        - ./src/test/main.java
       
 This is dictated by the javadoc executable for creating a javadoc that has information on the different packages. I am working on a command for an individual file javadoc generator.
